### PR TITLE
Split multicast socket for UDPTransport

### PR DESCRIPTION
**Pull request by pdgendt**
Create a separate socket when creating an UDPTransport with a remote multicast address to receive and send messages.
This allows us to distinguish messages we sent ourselves.

## Description

Fixes # (issue)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code quality improvements to existing code or addition of tests

## Checklist

- [ ] The documentation has been adjusted accordingly
- [x] Tests have been added that prove the fix is effective or that the feature works
- [ ] The changes are documented in the changelog (docs/changelog.md)

### CODE REVIEW

File: xknx/io/transport/udp_transport.py [hunk 1]
```diff
@@ -72,10 +76,16 @@ def __init__(
...
 
         self.callbacks = []
+        self.local_addr_assigned: tuple[str, int] | None = None
         self.transport: asyncio.DatagramTransport | None = None
+        self.mcast_transport: asyncio.DatagramTransport | None = None
 
     def data_received_callback(self, raw: bytes, source: tuple[str, int]) -> None:
         """Parse and process KNXIP frame. Callback for having received an UDP packet."""
+        if self.multicast and source == self.local_addr_assigned:
+            knx_logger.debug("Received echoed KNXIPFrame")
```
Comment (farmio) [inline xknx/io/transport/udp_transport.py:86]:
```suggestion
            raw_socket_logger.debug("Discarded echoed datagram")
```
I think this is better handled by `raw_socket_logger` since we haven't parsed it to a KNXIPFrame yet.

File: test/integration_tests/routing_multicast_test.py [hunk 2]
```diff
@@ -0,0 +1,42 @@
...
+            connection_config=ConnectionConfig(connection_type=ConnectionType.ROUTING),
+            telegram_received_cb=routing2_mock,
+        ),
+    ):
+        await xknx1.telegrams.put(msg)
+        await asyncio.sleep(0.1)
+
+        msg.direction = TelegramDirection.INCOMING
+        routing1_mock.assert_not_called()
+        routing2_mock.assert_called_with(msg)
```
Comment (farmio) [inline test/integration_tests/routing_multicast_test.py:42]:
```suggestion
from xknx.telegram.tpci import TDataGroup
from xknx.util import asyncio_timeout


async def test_routing_indication_multicast() -> None:
    """Test exchanging routing indication using multicast."""
    routing1_mock = Mock()
    data_received = asyncio.Event()
    received_data: Telegram | None = None

    def routing2_callback(telegram: Telegram) -> None:
        """Set test data from receiving xknx instance."""
        nonlocal received_data
        received_data = telegram
        data_received.set()

    msg = Telegram(
        destination_address=GroupAddress("1/2/2"),
        source_address=IndividualAddress("1.1.1"),
        payload=GroupValueWrite(DPTBinary(1)),
        tpci=TDataGroup(),
    )

    async with (
        XKNX(
            connection_config=ConnectionConfig(connection_type=ConnectionType.ROUTING),
            telegram_received_cb=routing1_mock,
        ) as xknx1,
        XKNX(
            connection_config=ConnectionConfig(connection_type=ConnectionType.ROUTING),
            telegram_received_cb=routing2_callback,
        ),
    ):
        await xknx1.telegrams.put(msg)
        async with asyncio_timeout(1):
            await data_received.wait()

        msg.direction = TelegramDirection.INCOMING
        routing1_mock.assert_not_called()
        assert received_data == msg
```
We should avoid `sleep` in tests.

**Review by farmio — CHANGES_REQUESTED** [review]

**Comment by farmio** [comment]
I've tested this locally (with Gira and Enertex IP Secure Routers) and it works fine.

One thing I found is that the integration test could be problematic eventually. It sends real KNX telegrams out to the network - so if someone runs the `pytest` locally with a non-knx-secure environment - this may trigger actual things in their KNX installation. Using `local_ip="127.0.0.1"` doesn't seem to work at my machine. So there are 3 workarounds I can think of:
- use a non-standard multicast group (not ideal - some users may have test environments using the same)
- use secure routing - but in the current implementation this adds quite a bit of time (>3 seconds) to the tests when trying to synchronize the secure timer. Maybe this can be mock-patched to work better, but I haven't succeeded in some quick trys.
- exclude it from running locally and only run it in CI (or locally when called manually)

**Comment by pdgendt** [comment]
> I've tested this locally (with Gira and Enertex IP Secure Routers) and it works fine.

Nice!

> One thing I found is that the integration test could be problematic eventually. It sends real KNX telegrams out to the network - so if someone runs the `pytest` locally with a non-knx-secure environment - this may trigger actual things in their KNX installation. Using `local_ip="127.0.0.1"` doesn't seem to work at my machine. So there are 3 workarounds I can think of:

I also tried `local_ip="127.0.0.1"` which seems to work as expected?

> * use a non-standard multicast group (not ideal - some users may have test environments using the same)
> * use secure routing - but in the current implementation this adds quite a bit of time (>3 seconds) to the tests when trying to synchronize the secure timer. Maybe this can be mock-patched to work better, but I haven't succeeded in some quick trys.
> * exclude it from running locally and only run it in CI (or locally when called manually)

If the local IP isn't a valid solution, I'd prefer option 1 here.

**Comment by farmio** [comment]
CI seems to work fine with 127.0.0.1
On what OS did you test it? Didn't work on macOS for me.

**Comment by pdgendt** [comment]
> CI seems to work fine with 127.0.0.1 On what OS did you test it? Didn't work on macOS for me.

Ubuntu, but the previous test already failed on my mac with `No route to host`.

**Comment by farmio** [comment]
> WARNING  xknx.log:udp_transport.py:53 Error received: [Errno 49] Can't assign requested address

here

**Comment by farmio** [comment]
Hm... what do you think about 224.0.0.254 ? https://www.rfc-editor.org/rfc/rfc4727.html

**Review by farmio — APPROVED** [review]
Nice 👍 Thanks for your contribution!
